apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-1
    app.kubernetes.io/part-of: purple-mermaid
  name: nodejs-1
  namespace: rorai
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: nodejs-1
status:
  loadBalancer: {}
